name: build & push image

on:
  push:
    tags:
      - "*"

jobs:
  build-image:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: uivmm/taskfile

      - uses: docker/setup-qemu-action@v2

      - id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            TASKFILE_VERSION=3.31.0
